# Generated by Django 5.2.3 on 2025-08-18 11:37

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('ID_facule', models.AutoField(primary_key=True, serialize=False)),
                ('description_faculte', models.CharField(max_length=50, unique=True, verbose_name='Faculté')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('ID_promotion', models.AutoField(primary_key=True, serialize=False)),
                ('description_promotion', models.CharField(max_length=50, unique=True, verbose_name='Promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('ID_section', models.AutoField(primary_key=True, serialize=False)),
                ('description_section', models.CharField(max_length=50, unique=True, verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('matricule', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Matricule')),
                ('nom_etudiant', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom_etudiant', models.CharField(max_length=50, verbose_name='Prénom')),
                ('postnom_etudiant', models.CharField(max_length=50, verbose_name='Postnom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, verbose_name='Sexe')),
                ('date_naissance', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2025, 8, 18)), django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1))], verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=120, verbose_name='Lieu de naissance')),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='etudiants.faculte')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='etudiants.promotion')),
            ],
        ),
        migrations.AddField(
            model_name='faculte',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultes', to='etudiants.section'),
        ),
    ]
