# Generated by Django 5.2.3 on 2025-08-20 11:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2025, 8, 20)), django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1))], verbose_name='Date de naissance'),
        ),
    ]
