# Generated by Django 5.2.3 on 2026-05-31 16:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_etudiant_qr_code_etudiant_qr_code_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2026, 5, 31)), django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1))], verbose_name='Date de naissance'),
        ),
    ]
