"""
Django settings for carte_etudiant project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = BASE_DIR.parent

load_dotenv(REPO_ROOT / ".env")
load_dotenv(REPO_ROOT / "backend_student" / ".env")
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY manquant. Copiez .env.example en .env à la racine du dépôt."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage', # <-- Ajouté ici
    'cloudinary',         # <-- Ajouté ici
    'etudiants'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <-- Ajouté ici
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'carte_etudiant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'carte_etudiant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Local : Postgres Docker (backend_student/). Prod : Neon / autre via DATABASE_URL.
_default_db_url = (
    "postgres://studentcard_user:studentcard_dev_password@127.0.0.1:5434/studentcard_db"
)
DATABASE_URL = os.getenv("DATABASE_URL", _default_db_url)
DATABASES = {
    "default": dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=DATABASE_URL.startswith(("postgres://", "postgresql://"))
        and "localhost" not in DATABASE_URL
        and "127.0.0.1" not in DATABASE_URL,
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#
# # On utilise le stockage simple pour éviter que WhiteNoise ne bloque le CSS
# STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'
#
# # Configuration Cloudinary pour sauver les QR Codes
# CLOUDINARY_STORAGE = {
#     'CLOUDINARY_URL': os.getenv('CLOUDINARY_URL')
# }
# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
# MEDIA_URL = '/media/'
#
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#
# # Astuce de pro : Render fournit automatiquement 'RENDER_EXTERNAL_URL'.
# # Si on est sur Render, le QR Code utilisera la vraie URL publique !
# DOMAIN = os.getenv('RENDER_EXTERNAL_URL', 'http://127.0.0.1:8000')

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuration Cloudinary pour sauver les QR Codes
CLOUDINARY_STORAGE = {
    'CLOUDINARY_URL': os.getenv('CLOUDINARY_URL')
}

# --- NOUVELLE GESTION DES FICHIERS (DJANGO 5+) ---
# Remplace les anciens STATICFILES_STORAGE et DEFAULT_FILE_STORAGE
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.StaticFilesStorage",
    },
}

MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

def _public_app_domain() -> str:
    """URL publique de l'app (QR codes). Hugging Face définit SPACE_HOST automatiquement."""
    space_host = os.getenv("SPACE_HOST", "").strip()
    if space_host:
        return f"https://{space_host}".rstrip("/")
    for key in ("PUBLIC_APP_URL", "HuggingFace_URL", "RENDER_EXTERNAL_URL"):
        value = os.getenv(key, "").strip()
        if value:
            if not value.startswith(("http://", "https://")):
                value = f"https://{value}"
            return value.rstrip("/")
    return "http://127.0.0.1:8000"


DOMAIN = _public_app_domain()


def _build_csrf_trusted_origins() -> list[str]:
    origins: list[str] = []
    if DOMAIN.startswith(("http://", "https://")):
        origins.append(DOMAIN)
    space_host = os.getenv("SPACE_HOST", "").strip()
    if space_host:
        origins.append(f"https://{space_host}")
    for raw in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(","):
        origin = raw.strip()
        if not origin:
            continue
        if not origin.startswith(("http://", "https://")):
            origin = f"https://{origin}"
        origins.append(origin.rstrip("/"))
    return list(dict.fromkeys(origins))


CSRF_TRUSTED_ORIGINS = _build_csrf_trusted_origins()

# Hugging Face / Render : HTTPS terminé au proxy, Django voit souvent HTTP en amont.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

_on_https = DOMAIN.startswith("https://") or bool(os.getenv("SPACE_HOST"))
if _on_https:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
